### ISSUE TITLE
The requirements.txt file

### ISSUE THREAD

**Issue by DevilXD** [pytest-dev/pytest-order#34]
Hello o/

This is just a quick "please consider" issue, partially related to the PRs I've recently done. This project could really use a `requirements.txt`-like file, enlisting every pip package needed to develop / work on the plugin - pretty much everything needed to run the tests and build documentation. From the top of my head, those would be roughly:

```
pytest>=3.7.0
sphinx  # need minimal version (any additional sphinx packages?)
pytest-mock  # need minimal version
pytest-dependency  # need minimal version
pytest-xdist  # need minimal version
```

Because `requirements.txt` specifically, can usually be found in the root folder of the project, and contains dependencies needed for the project to run (base requirements), I recommend going with a different name, such as `requirements_dev.txt`, or alternatively, naming it `requirements.txt`, but placing it in the tests folder (should be communicative enough, that those are for development only - can always add a comment inside).

With that in place, one can then do `pip install -r requirements_dev.txt` and already be good to go, in regards of testing the plugin (no failing or erroring out tests, because of missing packages) and building its documentation.

I'd place in such a PR myself, but I figured you'd have a more extensive knowledge on which minimal versions this thing can run on. I've installed the latest ones. and the seemed to work just fine, so defining minimal versions should be sufficient.

**Side-note:** It appears that `setup.py` lists `pytest` as a requirement: `install_requires=["pytest>=3.7"]`. Because of this, in addition to the "dev requirements" file, it may be a good idea to add a standard `requirements.txt` file in the root directory (right next to `setup.py`), with just `pytest>=3.7.0` inside. You can then either leave the `pytest>=3.7.0` line in the dev requirements, or use `-r <path_to_base_requirements>` to avoid having base requirements defined in two different places. For reference, you can see my `aRez` library as an example:

https://github.com/DevilXD/aRez/blob/master/requirements.txt
https://github.com/DevilXD/aRez/blob/master/requirements_dev.txt
https://github.com/DevilXD/aRez/blob/master/docs/requirements.txt
https://github.com/DevilXD/aRez/blob/master/tests/requirements.txt

**Side-side-note:** Another thing I've spotted in `setup.py`, is you using `from pytest_order import __version__`, which may sound okay at first, but is actually really bad, as long as your project contains any dependencies. The reason is quite simple: while you define the dependencies to install in `setup.py` (via `install_requires`), the file has to actually execute to install them. And it won't be able to execute, because if you don't have `pytest` installed, the `from pytest_order import __version__` line is going to fail with an `ImportError` (deep inside your plugin, on any line where you do `import pytest`), which will fail the whole setup, which won't install dependencies - duh. You can test this by uninstalling pytest, and then trying to build the plugin from source, via `pip install git+https://github.com/pytest-dev/pytest-order`. You may want to fix that.

For more information on this, please refer to the setup.py docs, or my `aRez` library:
https://packaging.python.org/guides/distributing-packages-using-setuptools/#version
https://packaging.python.org/guides/single-sourcing-package-version/#single-sourcing-the-version
https://github.com/DevilXD/aRez/blob/master/setup.py#L6

**Comment by mrbean-bremen** [comment]
The standard for pytest plugins is to test via tox (as also mentioned in the README), and the requirements are respectively in `tox.ini`. This was actually a precondition for the transition to `pytest_dev`, but it was already there in `pytest_ordering`, so I just left it as is.
I can add additional `requirements.txt` and `requirements_dev.txt` files for convenience, and a `requirements.txt` for `sphinx` (I prefer not to mix development and doc generation).
As for `__version__` - I agree that it may not be ideal as is, but I already changed this from the previous state. Initially the whole plugin has been in `__init__.py` - I moved that into separate modules and left only `__version__` there specifically to avoid having a dependency on `pytest`. The doc generation in the CI also reads the version from there, and it does not have pytest installed. As for installing `pytest_order` from source - I just did this in a bare virtual env and it works fine. Where do you get a dependency to `pytest`?

**Comment by mrbean-bremen** [comment]
Reading through the [documentation](https://packaging.python.org/guides/single-sourcing-package-version/#single-sourcing-the-version), you can see that one method they propose (although not the most preferred one, under 6.) is exactly this, with the warning that this will be problematic if `__init__.py` imports other stuff (which we don't). Though I have also been using method 3 (dedicated `version.py`) elsewhere and may change it accordingly.

**Comment by DevilXD** [comment]
Hmm, actually in this case, since your `__init__.py` doesn't have further imports inside, it should be fine. [This way is referred to in #6 of the setup.py docs](https://packaging.python.org/guides/single-sourcing-package-version/#single-sourcing-the-version). I haven't checked the contents of that one, my bad. You can ignore the last note >.>

> I can add additional requirements.txt and requirements_dev.txt files for convenience

Yeah, this is pretty much purely for convenience, again - I made this issue solely for you to consider adding that, as those are generally good to have, especially the development packages one. All-in-one, or split over separate base, tests, and docs requirements like I have in my library - should be good enough, as long as it's there "for future generations" :stuck_out_tongue:

**Comment by mrbean-bremen** [comment]
Looks like we have been reading the same documentation at the same time 😄

**Comment by DevilXD** [comment]
Hah, yeah. In my case, I have a bunch of imports in my `__init__.py` file, that eventually lead to `import aiohttp`, and that's where it all crashes down, as long as `aiohttp` isn't installed :sweat: Hence my solution of reading the file directly, and using regex to extract the version string, as you saw.

**Comment by mrbean-bremen** [comment]
@DevilXD - I added a couple of `requirement.txt` files, but decided to leave the version alone as is - no real advantage in changing it.

**Comment by DevilXD** [comment]
Looks good to me! =)

**Comment by mrbean-bremen** [comment]
Thanks!
