### ISSUE TITLE
Move to pytest-dev organization

### ISSUE THREAD

**Issue by mrbean-bremen** [pytest-dev/pytest-order#4]
This is a reminder that if pytest-ordering will not be revived after some time (arbitrary date: December 1st), this may be moved to pytest-dev (see also [this issue](https://github.com/ftobia/pytest-ordering/issues/32)).

[Preconditions](https://github.com/pytest-dev/pytest/blob/master/CONTRIBUTING.rst#submitting-plugins-to-pytest-dev):
- [x] PyPI presence with packaging metadata that contains a pytest- prefixed name, version number, authors, short and long description.
- [x] a tox configuration for running tests using tox.
- [x] a README describing how to use the plugin and on which platforms it runs.
- [x] a LICENSE file containing the licensing information, with matching info in its packaging metadata.
- [x] an issue tracker for bug reports and enhancement requests.
- [x] a changelog.
- [x] clarify handling of CI (GH actions) and documentation (GH pages) - will be adapted automatically 
- [x] submit your plugin by subscribing to the pytest-dev mail list and writing a mail pointing to your existing pytest plugin
- [x] wait for confirmation (or not) 
- [ ] adapt links in documentation etc after move -> handled in separate issue

**Comment by mrbean-bremen** [comment]
Doesn't look like pytest-ordering will be revived, anyway will wait until (and if) this is one is really used by a few people before proceeding.

**Comment by mrbean-bremen** [comment]
[Another try](https://github.com/ftobia/pytest-ordering/issues/32#issuecomment-753592628) to get a response, will probably wait until March before continuing.

**Comment by HMaker** [comment]
This library is specially important in cases where we want to run unit tests before integration tests so we can make sure all units are working when some error happen in integration test. It really deserves to be officially part of pytest ecosystem.

**Comment by mrbean-bremen** [comment]
Thanks - I have seen often enough that good projects die because there is no maintainer (there are valid reasons why someone won't or can't maintain a project anymore), and having a caring organization is a good way to ensure that projects can survive. I came upon this project by chance - didn't plan to fork it, but as I saw that there are some some helpful PRs done, but not integrated, and the project is small but often used, I thought it wasteful to leave it that way... Will probably go for the integration next week, provided the maintainer does not respond.
