### ISSUE TITLE
The test class and the test method exist together

### ISSUE THREAD

**Issue by tianya66** [pytest-dev/pytest-order#43]
When executing, the test methods in the test class are run in the expected order. What should I do

**Comment by tianya66** [comment]
The test classes are executed sequentially, and the methods in the test classes are executed sequentially

**Comment by tianya66** [comment]
In the meantime, I want to use the --order-scope=class option

**Comment by mrbean-bremen** [comment]
Not sure I understand what you mean. Could you please add a description to the issue?

**Comment by tianya66** [comment]
I'm so sorry；There are multiple test classes，Each test class contains multiple test methods，I want to perform a sequential sort for the test class，The test methods are also kept in order relative to the class。

**Comment by mrbean-bremen** [comment]
If I understand you correctly, you have one or more test modules, with multiple test classes, and you want the order of the tests _not_ to be changed? Can you show a simple example (say, 2 classes with 2 or 3 empty test methods each, or whatever is needed to show your case) and show in what order they are executed, and in what order do you want them executed? From your description, it looks like you don't want any reordering at all, but I'm obviously not understanding something here.

As a side note: there is no need to put the issue description into separate comments, just add a description above.
