### ISSUE TITLE
PytestUnknownMarkWarning is raised

### ISSUE THREAD

**Issue by eugenkleinschmidt** [pytest-dev/pytest-order#54]
I think with latest pytest and `filterwarnings = error` I got this warning which is catch as error.

```
@pytest.mark.order(after="TestFirst")
.tox\py\lib\site-packages\_pytest\mark\structures.py:510: in __getattr__
    warnings.warn(
E   pytest.PytestUnknownMarkWarning: Unknown pytest.mark.order - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
```

**Comment by ArchangeGabriel** [comment]
Actually I have the same issue while running the test suite of pytest-order (I’m packaging for Arch Linux), [which seemingly results in most tests failing](https://gist.github.com/ArchangeGabriel/29b9a869a3d49ee4c694b7c47936938b).
Not sure if that’s the same issue, but I thought it could be related.

**Comment by eugenkleinschmidt** [comment]
This is what I get:

```
>pip freeze | grep pytest-order
pytest-order==1.0.0
```

```
>pytest --markers | grep order
@pytest.mark.order: specify ordering information for when tests should run in relation to one another. Provided by pytest-order. See also: https://pytest-dev.github.io/pytest-order/
```

**Comment by mrbean-bremen** [comment]
Did you find out something here? I'm quite sure that this is an issue with the environment and not with pytest-order, otherwise this would have been noticed long ago.

**Comment by eugenkleinschmidt** [comment]
I cannot reproduce it any more. Sorry for the incontinence 😅
Can be closed

**Comment by mrbean-bremen** [comment]
Thanks - closing in this case.
