### ISSUE TITLE
LICENSE only specifies original author

### ISSUE THREAD

**Issue by juliangilbey** [pytest-dev/pytest-order#56]
Hi!
Thanks for taking on this plugin and improving it!
I noticed that the LICENSE file only specifies the original copyright holder; have the other authors transferred their copyright to him, or are the contributions jointly owned, or something else? It would be good for the LICENSE file to be corrected if the copyright has changed since the package was adopted by you.

**Comment by mrbean-bremen** [comment]
Hm, I'm not a lawyer, and I'm not sure what the correct way to do this is. I personally don't care much about the copyright (e.g. could leave it as is), but if I would change it, it would be probably something like "Copyright by pytest-order contributors", as is done in some other projects I know. I actually don't know if there are any rules how to handle the copyright for forks - probably have to leave the copyright and add a new one on top?

If you know more about this I would happily be educated :)

**Comment by mrbean-bremen** [comment]
CC @ftobia

**Comment by juliangilbey** [comment]
Thanks @mrbean-bremen!

I too am not a lawyer.   As far as I understand, copyright is by default owned by the creator of a work, but they can assign it to someone else.  But the contributors haven't assigned their modifications to Frank.  So adding something like "Modifications copyright by pytest-order contributors, as listed in AUTHORS" in addition to the original copyright notice seems to be a perfectly reasonable thing to do, and as you say, this is what several open source projects do.

Best wishes,

Julian

**Comment by mrbean-bremen** [comment]
Thanks, that sounds good.
