### ISSUE TITLE
Ordering tests based on execution time

### ISSUE THREAD

**Issue by bmarchenko** [pytest-dev/pytest-order#61]
In some cases, ordering tests by execution time may speed up the total runtime significantly. For example, consider the following situation with 5 tests executed on 2 workers:
![image](https://user-images.githubusercontent.com/759203/171625663-3f608318-f4ef-4286-acf7-6c8ccf96532c.png)

Especially, this is important for many tests with different runtime where manual ordering is rather difficult. 

The implementation can  be done through a history file where the execution time of a previous run can be kept.

**Comment by mrbean-bremen** [comment]
Hm, I can see why this would make sense, but I don't really see this as a part of `pytest-order` - it is too specialized for that. It could make sense to add a separate plugin that does this. I'm not sure if there already is a plugin that collects the run times of tests - I think there are more than a thousand plugins out there, so it may well be that something already exists, and that could be adapted. Or somebody (maybe even myself) could just write a new plugin for that...

**Comment by mrbean-bremen** [comment]
After a cursory glance at the plugin list, I found [pytest-split](https://pypi.org/project/pytest-split/) - maybe you can already use this.

**Comment by mrbean-bremen** [comment]
@bmarchenko - have you looked in `pytest-split-tests`?

**Comment by mrbean-bremen** [comment]
Closing due to missing feedback, and out of scope feature.
