### ISSUE TITLE
I can run pytest-order example

### ISSUE THREAD

**Issue by dmitrysbor** [pytest-dev/pytest-order#65]
I  use venv with following packages:
Python 3.10.4
pytest Version: 7.1.2

and I installed pytest-order like this:
pip3 install pytest-order

When I try to run this example:
import pytest

@pytest.mark.order(2)
def test_foo():
    assert True

@pytest.mark.order(1)
def test_bar():
    assert True

I shows that order marks are not picked up:
 
(.venv) dafanasyev@TCCIT0664:~/daps-functional-tests$ pytest-3 -vv test_order.py 
======================================================================= test session starts ========================================================================
platform linux -- Python 3.10.4, pytest-6.2.5, py-1.10.0, pluggy-0.13.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/dafanasyev/daps-functional-tests
plugins: allure-pytest-2.9.45, testconfig-0.2.0
collected 2 items                                                                                                                                                  

test_order.py::test_foo PASSED                                                                                                                               [ 50%]
test_order.py::test_bar PASSED                                                                                                                               [100%]

========================================================================= warnings summary 
**test_order.py:3
  /home/dafanasyev/daps-functional-tests/test_order.py:3: PytestUnknownMarkWarning: Unknown pytest.mark.order - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.order(2)**

**test_order.py:7
  /home/dafanasyev/daps-functional-tests/test_order.py:7: PytestUnknownMarkWarning: Unknown pytest.mark.order - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.order(1)**

-- Docs: https://docs.pytest.org/en/stable/warnings.html
================================================================== 2 passed, 3 warnings in 1.07s 

How can diagnose and solve problem?

**Comment by mrbean-bremen** [comment]
`pytest-order` does not show up in the list of pytest plugins, so it is not installed - are you sure the tests run in the same environment where `pytest-order` is installed? Does `pip list` run in the same environment show `pytest-order`?

**Comment by dmitrysbor** [comment]
I've repeated plugin installation with the same result:
(.venv) dafanasyev@TCCIT0664:~/daps-functional-tests$ pip3 install pytest-order
Requirement already satisfied: pytest-order in ./.venv/lib/python3.10/site-packages (1.0.1)
Requirement already satisfied: pytest>=6.2.4 in ./.venv/lib/python3.10/site-packages (from pytest-order) (7.1.2)
Requirement already satisfied: packaging in ./.venv/lib/python3.10/site-packages (from pytest>=6.2.4->pytest-order) (21.3)
Requirement already satisfied: pluggy<2.0,>=0.12 in ./.venv/lib/python3.10/site-packages (from pytest>=6.2.4->pytest-order) (1.0.0)
Requirement already satisfied: iniconfig in ./.venv/lib/python3.10/site-packages (from pytest>=6.2.4->pytest-order) (1.1.1)
Requirement already satisfied: tomli>=1.0.0 in ./.venv/lib/python3.10/site-packages (from pytest>=6.2.4->pytest-order) (2.0.1)
Requirement already satisfied: attrs>=19.2.0 in ./.venv/lib/python3.10/site-packages (from pytest>=6.2.4->pytest-order) (21.4.0)
Requirement already satisfied: py>=1.8.2 in ./.venv/lib/python3.10/site-packages (from pytest>=6.2.4->pytest-order) (1.11.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in ./.venv/lib/python3.10/site-packages (from packaging->pytest>=6.2.4->pytest-order) (3.0.9)
(.venv) dafanasyev@TCCIT0664:~/daps-functional-tests$ pytest-3 -vv test_order.py 
======================================================================= test session starts ========================================================================
platform linux -- Python 3.10.4, pytest-6.2.5, py-1.10.0, pluggy-0.13.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/dafanasyev/daps-functional-tests
plugins: allure-pytest-2.9.45, testconfig-0.2.0
collected 2 items                                                                                                                                                  

test_order.py::test_foo PASSED                                                                                                                               [ 50%]
test_order.py::test_bar PASSED                                                                                                                               [100%]

========================================================================= warnings summary =========================================================================
../../../usr/lib/python3/dist-packages/pluggy/hooks.py:262
  /usr/lib/python3/dist-packages/pluggy/hooks.py:262: DeprecationWarning: Support for __multicall__ is now deprecated and will beremoved in an upcoming release.
    warnings.warn(

test_order.py:3
  /home/dafanasyev/daps-functional-tests/test_order.py:3: PytestUnknownMarkWarning: Unknown pytest.mark.order - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.order(2)

test_order.py:7
  /home/dafanasyev/daps-functional-tests/test_order.py:7: PytestUnknownMarkWarning: Unknown pytest.mark.order - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.order(1)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
================================================================== 2 passed, 3 warnings in 1.57s ===================================================================
(.venv) dafanasyev@TCCIT0664:~/daps-functional-tests$

**Comment by dmitrysbor** [comment]
I repeated plugin installation with the same result:
`
(.venv) dafanasyev@TCCIT0664:~/daps-functional-tests$ pip3 install pytest-order
Requirement already satisfied: pytest-order in ./.venv/lib/python3.10/site-packages (1.0.1)
Requirement already satisfied: pytest>=6.2.4 in ./.venv/lib/python3.10/site-packages (from pytest-order) (7.1.2)
Requirement already satisfied: packaging in ./.venv/lib/python3.10/site-packages (from pytest>=6.2.4->pytest-order) (21.3)
Requirement already satisfied: pluggy<2.0,>=0.12 in ./.venv/lib/python3.10/site-packages (from pytest>=6.2.4->pytest-order) (1.0.0)
Requirement already satisfied: iniconfig in ./.venv/lib/python3.10/site-packages (from pytest>=6.2.4->pytest-order) (1.1.1)
Requirement already satisfied: tomli>=1.0.0 in ./.venv/lib/python3.10/site-packages (from pytest>=6.2.4->pytest-order) (2.0.1)
Requirement already satisfied: attrs>=19.2.0 in ./.venv/lib/python3.10/site-packages (from pytest>=6.2.4->pytest-order) (21.4.0)
Requirement already satisfied: py>=1.8.2 in ./.venv/lib/python3.10/site-packages (from pytest>=6.2.4->pytest-order) (1.11.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in ./.venv/lib/python3.10/site-packages (from packaging->pytest>=6.2.4->pytest-order) (3.0.9)
(.venv) dafanasyev@TCCIT0664:~/daps-functional-tests$ pytest-3 -vv test_order.py 
======================================================================= test session starts ========================================================================
platform linux -- Python 3.10.4, pytest-6.2.5, py-1.10.0, pluggy-0.13.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/dafanasyev/daps-functional-tests
plugins: allure-pytest-2.9.45, testconfig-0.2.0
collected 2 items                                                                                                                                                  

test_order.py::test_foo PASSED                                                                                                                               [ 50%]
test_order.py::test_bar PASSED                                                                                                                               [100%]

========================================================================= warnings summary =========================================================================
../../../usr/lib/python3/dist-packages/pluggy/hooks.py:262
  /usr/lib/python3/dist-packages/pluggy/hooks.py:262: DeprecationWarning: Support for __multicall__ is now deprecated and will beremoved in an upcoming release.
    warnings.warn(

test_order.py:3
  /home/dafanasyev/daps-functional-tests/test_order.py:3: PytestUnknownMarkWarning: Unknown pytest.mark.order - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.order(2)

test_order.py:7
  /home/dafanasyev/daps-functional-tests/test_order.py:7: PytestUnknownMarkWarning: Unknown pytest.mark.order - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.order(1)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
================================================================== 2 passed, 3 warnings in 1.57s ===================================================================
(.venv) dafanasyev@TCCIT0664:~/daps-functional-tests$ 
`

**Comment by mrbean-bremen** [comment]
Hm, I guess `pytest-3` is a symlink to `pytest`? is `pytest` installed in the same environment, or do you use a globally installed `pytest` (which may not use your enviroment)?

**Comment by mrbean-bremen** [comment]
And can you please show the output of `pip list` or `pip freeze`?

**Comment by dmitrysbor** [comment]
(.venv) dafanasyev@TCCIT0664:/home/daps-functional-tests$ which pytest-3
/usr/bin/pytest-3
(.venv) dafanasyev@TCCIT0664:/home/daps-functional-tests$ ls -l /usr/bin/pytest-3
-rwxr-xr-x 1 root root 953 фев  9  2022 /usr/bin/pytest-3

(.venv) dafanasyev@TCCIT0664:~/daps-functional-tests$ pip list
Package                Version
---------------------- -----------
allure-pytest          2.9.45
allure-python-commons  2.9.45
attrs                  21.4.0
certifi                2022.5.18.1
charset-normalizer     2.0.12
elastic-transport      8.4.0
elasticsearch          8.4.1
execnet                1.9.0
idna                   3.3
iniconfig              1.1.1
mysql-connector-python 8.0.30
packaging              21.3
pip                    22.0.2
pluggy                 1.0.0
protobuf               3.20.1
py                     1.11.0
pyparsing              3.0.9
pytest                 7.1.2
pytest-forked          1.4.0
pytest-order           1.0.1
pytest-xdist           2.5.0
requests               2.27.1
setuptools             59.6.0
six                    1.16.0
tomli                  2.0.1
urllib3                1.26.9

**Comment by mrbean-bremen** [comment]
Hm, that's strange - in your pytest run neither `pytest-xdist` nor `pytest-order` show up as plugins. What does `pytest --fixtures` give you?

**Comment by mrbean-bremen** [comment]
Actually, as you have`pytest` installed in the enviroment, there is no reason to call `pytest-3`, just use `pytest` or `python -m pytest` instead.

**Comment by dmitrysbor** [comment]
(.venv) dafanasyev@TCCIT0664:~/daps-functional-tests$ pytest --fixtures
======================================================================= test session starts ========================================================================
platform linux -- Python 3.10.4, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/dafanasyev/daps-functional-tests
plugins: forked-1.4.0, order-1.0.1, allure-pytest-2.9.45, xdist-2.5.0
collected 156 items                                                                                                                                                
cache -- .venv/lib/python3.10/site-packages/_pytest/cacheprovider.py:510
    Return a cache object that can persist state between testing sessions.

capsys -- .venv/lib/python3.10/site-packages/_pytest/capture.py:878
    Enable text capturing of writes to ``sys.stdout`` and ``sys.stderr``.

capsysbinary -- .venv/lib/python3.10/site-packages/_pytest/capture.py:895
    Enable bytes capturing of writes to ``sys.stdout`` and ``sys.stderr``.

capfd -- .venv/lib/python3.10/site-packages/_pytest/capture.py:912
    Enable text capturing of writes to file descriptors ``1`` and ``2``.

capfdbinary -- .venv/lib/python3.10/site-packages/_pytest/capture.py:929
    Enable bytes capturing of writes to file descriptors ``1`` and ``2``.

doctest_namespace [session scope] -- .venv/lib/python3.10/site-packages/_pytest/doctest.py:731
    Fixture that returns a :py:class:`dict` that will be injected into the
    namespace of doctests.

pytestconfig [session scope] -- .venv/lib/python3.10/site-packages/_pytest/fixtures.py:1334
    Session-scoped fixture that returns the session's :class:`pytest.Config`
    object.

record_property -- .venv/lib/python3.10/site-packages/_pytest/junitxml.py:282
    Add extra properties to the calling test.

record_xml_attribute -- .venv/lib/python3.10/site-packages/_pytest/junitxml.py:305
    Add extra xml attributes to the tag for the calling test.

record_testsuite_property [session scope] -- .venv/lib/python3.10/site-packages/_pytest/junitxml.py:343
    Record a new ``<property>`` tag as child of the root ``<testsuite>``.

tmpdir_factory [session scope] -- .venv/lib/python3.10/site-packages/_pytest/legacypath.py:295
    Return a :class:`pytest.TempdirFactory` instance for the test session.

tmpdir -- .venv/lib/python3.10/site-packages/_pytest/legacypath.py:302
    Return a temporary directory path object which is unique to each test
    function invocation, created as a sub directory of the base temporary
    directory.

caplog -- .venv/lib/python3.10/site-packages/_pytest/logging.py:487
    Access and control log capturing.

monkeypatch -- .venv/lib/python3.10/site-packages/_pytest/monkeypatch.py:29
    A convenient fixture for monkey-patching.

recwarn -- .venv/lib/python3.10/site-packages/_pytest/recwarn.py:29
    Return a :class:`WarningsRecorder` instance that records all warnings emitted by test functions.

tmp_path_factory [session scope] -- .venv/lib/python3.10/site-packages/_pytest/tmpdir.py:184
    Return a :class:`pytest.TempPathFactory` instance for the test session.

tmp_path -- .venv/lib/python3.10/site-packages/_pytest/tmpdir.py:199
    Return a temporary directory path object which is unique to each test
    function invocation, created as a sub directory of the base temporary
    directory.


------------------------------------------------------------------ fixtures defined from conftest ------------------------------------------------------------------
start_callback_server [session scope] -- conftest.py:43
    no docstring available

db_connection [session scope] -- conftest.py:59
    no docstring available

db_session [session scope] -- conftest.py:68
    no docstring available


---------------------------------------------------------------- fixtures defined from xdist.plugin ----------------------------------------------------------------
worker_id [session scope] -- .venv/lib/python3.10/site-packages/xdist/plugin.py:290
    Return the id of the current worker ('gw0', 'gw1', etc) or 'master'
    if running on the master node.

testrun_uid [session scope] -- .venv/lib/python3.10/site-packages/xdist/plugin.py:299
    Return the unique id of the current test.


====================================================================== no tests ran in 0.03s =======================================================================

**Comment by mrbean-bremen** [comment]
Looks like still the wrong pytest is used. What about `python -m pytest --fixtures`?

**Comment by dmitrysbor** [comment]
I don't understand whtat the difference, but when I run it by pytest (not pythtes-3) example works with no warnings:

(.venv) dafanasyev@TCCIT0664:~/daps-functional-tests$ pytest -vv test_order.py 
======================================================================= test session starts ========================================================================
platform linux -- Python 3.10.4, pytest-7.1.2, pluggy-1.0.0 -- /home/dafanasyev/daps-functional-tests/.venv/bin/python3
cachedir: .pytest_cache
rootdir: /home/dafanasyev/daps-functional-tests
plugins: forked-1.4.0, order-1.0.1, allure-pytest-2.9.45, xdist-2.5.0
collected 2 items                                                                                                                                                  

test_order.py::test_bar PASSED                                                                                                                               [ 50%]
test_order.py::test_foo PASSED                                                                                                                               [100%]

======================================================================== 2 passed in 0.77s =========================================================================
(.venv) dafanasyev@TCCIT0664:~/daps-functional-tests$

**Comment by dmitrysbor** [comment]
.venv) dafanasyev@TCCIT0664:~/daps-functional-tests$ python -m pytest --fixtures
======================================================================= test session starts ========================================================================
platform linux -- Python 3.10.4, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/dafanasyev/daps-functional-tests
plugins: forked-1.4.0, order-1.0.1, allure-pytest-2.9.45, xdist-2.5.0
collected 156 items                                                                                                                                                
cache -- .venv/lib/python3.10/site-packages/_pytest/cacheprovider.py:510
    Return a cache object that can persist state between testing sessions.

capsys -- .venv/lib/python3.10/site-packages/_pytest/capture.py:878
    Enable text capturing of writes to ``sys.stdout`` and ``sys.stderr``.

capsysbinary -- .venv/lib/python3.10/site-packages/_pytest/capture.py:895
    Enable bytes capturing of writes to ``sys.stdout`` and ``sys.stderr``.

capfd -- .venv/lib/python3.10/site-packages/_pytest/capture.py:912
    Enable text capturing of writes to file descriptors ``1`` and ``2``.

capfdbinary -- .venv/lib/python3.10/site-packages/_pytest/capture.py:929
    Enable bytes capturing of writes to file descriptors ``1`` and ``2``.

doctest_namespace [session scope] -- .venv/lib/python3.10/site-packages/_pytest/doctest.py:731
    Fixture that returns a :py:class:`dict` that will be injected into the
    namespace of doctests.

pytestconfig [session scope] -- .venv/lib/python3.10/site-packages/_pytest/fixtures.py:1334
    Session-scoped fixture that returns the session's :class:`pytest.Config`
    object.

record_property -- .venv/lib/python3.10/site-packages/_pytest/junitxml.py:282
    Add extra properties to the calling test.

record_xml_attribute -- .venv/lib/python3.10/site-packages/_pytest/junitxml.py:305
    Add extra xml attributes to the tag for the calling test.

record_testsuite_property [session scope] -- .venv/lib/python3.10/site-packages/_pytest/junitxml.py:343
    Record a new ``<property>`` tag as child of the root ``<testsuite>``.

tmpdir_factory [session scope] -- .venv/lib/python3.10/site-packages/_pytest/legacypath.py:295
    Return a :class:`pytest.TempdirFactory` instance for the test session.

tmpdir -- .venv/lib/python3.10/site-packages/_pytest/legacypath.py:302
    Return a temporary directory path object which is unique to each test
    function invocation, created as a sub directory of the base temporary
    directory.

caplog -- .venv/lib/python3.10/site-packages/_pytest/logging.py:487
    Access and control log capturing.

monkeypatch -- .venv/lib/python3.10/site-packages/_pytest/monkeypatch.py:29
    A convenient fixture for monkey-patching.

recwarn -- .venv/lib/python3.10/site-packages/_pytest/recwarn.py:29
    Return a :class:`WarningsRecorder` instance that records all warnings emitted by test functions.

tmp_path_factory [session scope] -- .venv/lib/python3.10/site-packages/_pytest/tmpdir.py:184
    Return a :class:`pytest.TempPathFactory` instance for the test session.

tmp_path -- .venv/lib/python3.10/site-packages/_pytest/tmpdir.py:199
    Return a temporary directory path object which is unique to each test
    function invocation, created as a sub directory of the base temporary
    directory.


------------------------------------------------------------------ fixtures defined from conftest ------------------------------------------------------------------
start_callback_server [session scope] -- conftest.py:43
    no docstring available

db_connection [session scope] -- conftest.py:59
    no docstring available

db_session [session scope] -- conftest.py:68
    no docstring available


---------------------------------------------------------------- fixtures defined from xdist.plugin ----------------------------------------------------------------
worker_id [session scope] -- .venv/lib/python3.10/site-packages/xdist/plugin.py:290
    Return the id of the current worker ('gw0', 'gw1', etc) or 'master'
    if running on the master node.

testrun_uid [session scope] -- .venv/lib/python3.10/site-packages/xdist/plugin.py:299
    Return the unique id of the current test.


====================================================================== no tests ran in 0.04s =======================================================================
(.venv) dafanasyev@TCCIT0664:~/daps-functional-tests$

**Comment by dmitrysbor** [comment]
Thanks a lot!

**Comment by dmitrysbor** [comment]
Thanks again!

**Comment by mrbean-bremen** [comment]
> I don't understand whtat the difference, but when I run it by pytest (not pythtes-3) example works with no warnings

As I wrote, `pytest-3` links to a globally installed `pytest` version, which does not use your virtual environment. You need to use the version of `pytest` which is instealled inside the environment.
