### ISSUE TITLE
WIll it works if I mark test last in another module which is not called

### ISSUE THREAD

**Issue by dmitrysbor** [pytest-dev/pytest-order#66]
It's not issue, it's rather question.

Suppose, I have test which I'd like to run last  after all tests and it defined in separate module:
**test_check_all_logs_after_tests_run.py**
@pytest.mark.order("last")
def test_check_all_logs_after_tests_run():
             pass

and I would like that it be called last whenever test module I run. Will it works with pytest-order? I mean if I not run test_check_all_logs_after_tests_run.py directly? Is the any scope for this in pytest-order?

**Comment by mrbean-bremen** [comment]
Or maybe you mean that the test is automatically started after each test run without including it? That would not be possible.

**Comment by dmitrysbor** [comment]
Thanks anyway.

**Comment by mrbean-bremen** [comment]
A pytest plugin can only affect the tests that the running pytest knows - this is by design. Test not included into a test run will never be affected by plugins.
