### ISSUE TITLE
Ordering fixtures

### ISSUE THREAD

**Issue by orsinium** [pytest-dev/pytest-order#98]
The pytest-order doesn't order fixtures. Would this feature be in the scope of the plugin?

To reproduce:

```python
import pytest

@pytest.fixture
def fixt1():
    print(">>> fixt1")

@pytest.fixture
def fixt2(fixt1):
    print(">>> fixt2")

@pytest.mark.order("first")
@pytest.fixture
def fixt3():
    print(">>> fixt3")

def test_ex1(fixt2, fixt3):
    print(">>> test1")
```

Running:

```bash
python3 -m pytest -s
```

Output:

```
tests/test_example.py >>> fixt1
>>> fixt2
>>> fixt3
>>> test1
```

Expected:

```
tests/test_example.py >>> fixt3
>>> fixt1
>>> fixt2
>>> test1
```

**Comment by mrbean-bremen** [comment]
No, I don't think that this is in scope for this plugin. There is a [defined order of fixtures](https://docs.pytest.org/en/stable/reference/fixtures.html#fixture-instantiation-order), and to achieve the result you want you just have to reorder the fixtures in the test:
```py
def test_ex1(fixt3, fixt2):
    print(">>> test1")
```

**Comment by orsinium** [comment]
Thank you! I'll try the plugin, it seems to work, at least in simple cases.
